<h2>Neural Network Principles</h2>
Best YT Series on NN principles: <a href = "https://youtu.be/aircAruvnKk">https://youtu.be/aircAruvnKk</a>
<br><b>Neural networks</b>: Layered number values connected by some function. All a NN is is noded individual values connected by functions. It is, in the end, just a function of a bunch of functions with a bunch of weights and parameters.
<div style="overflow: hidden;">
    <img style="width: 350px; height: 300px;" align="left" src="https://i.gyazo.com/59f4ec6ef301ec665226c3550e32f2cb.png"></div>
<br><b>Perceptron</b>: A "vanilla" neural network, or a simple network with weights and biases + backward propagation.<br>
<b>Deep neural network</b>: A network with 2 or more hidden layers.<br>
<b>Width</b>: How many nodes in a layer<br>
<b>Depth</b>: How many layers there are<br>
<b>Node</b>: A numerical value and function. Every node in one layer is connected to the node in the next layer. So each layer nodes are connected to the next.<br>
<b>Activation0-n</b>: Activation is the actual activation of that individual node.<br>
<b>Activation Function</b>: Every node has an activation to it. An activation function limits and determines the number of the final result for that node. This can be sigmoid, hyperbolic tang and many others.<br>
<b>Hidden layers</b>: Layers between the I/O. They are just the middle layers.
<br><b>Parameters/weights</b>: Weights are arbitrary numbers whic determine the value of the node to the next layer. They are the lines between nodes./ You multply the activation by the weight then sum them and take the sigmoid function to determine how important that pixel is for the next layer. The number of layers and nodes after the pixels are also arbitrary.
<br><b>One hot encoding</b>: When 0 -> 1 is denoted for classification on the right most layer
<br><b>Mutually exclusive</b>: The resulting classification can only have 1 label as the output
<br><b>Non exclusive</b>: The resulting classification can have multiple labels
<br><b>Soft max</b>: An actvation function which creates categorical outputs which as a whole add up to 1. The point is to make 1 node the most likely output, allowing you to create a mutually exclusive result.
<br><b>Sigmoid</b>: An activation function which makes each category between 0 and 1. This allows for multi-label classification.
<br><b>Weighted sum</b>: If, for example we were to take this paramater, like in the above video, and sum them we would come up with the weighted sum
<div style="overflow: hidden;">
    <img style="width: 450px; height: 300px;" align="left" src="https://i.gyazo.com/09db9315617566d85efac2eb23687532.png">
</div>
<b>Sigmoid function</b>: Takes a larger number and pumps it into a range between 0, 1
<div style="overflow: hidden;">
    <img style="width: 450px; height: 300px;" align="left" src="https://i.gyazo.com/4ff4cc6fd40d4739a5b0b14eaf483ef4.png">
</div>
<b>Bias</b>: A value which curbs the activation of a parameter into the next node. Here is a solid <a href="https://youtu.be/aircAruvnKk?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&t=644">explaination</a>.
<div style="overflow: hidden;">
    <img style="width: 450px; height: 300px;" align="left" src="https://i.gyazo.com/4954c3e02a8b4b9d6e80368b4af090d0.png">
</div>
<b>Annotations</b>
<div style="overflow: hidden;">
    <img style="width: 450px; height: 300px;" align="left" src="https://i.gyazo.com/4954c3e02a8b4b9d6e80368b4af090d0.png">
</div>
*a<sub>L1</sub><sup>L2</sup>: Activation of node/neuron, bottom is layer index and top is the layer depth.
<br>*w<sub>L1, L2</sub>: Weight by layer coordinates
<br>*b<sub>L1</sub>: Bias by layer coordinate index within that layer.
<br><b>Cost function</b>: The cost of using the model against perfection. A number which increases the more lousy a model is. Basically you take the wrongness of each categorical result, find the difference and square it to estimate cost.
<br><b>Gradient</b>: We are basically finding minimums for the cost function. For typical 1d-3d planes this means we find the derivative and solve for 0 slope. However in n-dimensional graphs its called a gradient. Gradient is an upside down triangle.
<br><b>Training a neural network</b>: Making the cost function result as low as possible, simple calculus with a large number of dimensions, the first layer being the dimensions.
<br><b>Gradient descent step, learning rate</b>: A step/learning rate is a direction or increment of weights and baises from which the cost function gets lower.
<div style="overflow: hidden;">
    <img style="width: 450px; height: 450px;" align="left" src="https://i.gyazo.com/214d584937cc437d149d2f7d6eaa3d81.png">
</div>
<br><b>Step optimization</b>: A change in learning rate/step distance as the cost function decreases.
<br><b>Backward propagation</b>: One layer's weights propogate(Spread) the changes of the previous.In the below image imagine w<sub>i</sub> as w<sub>i-1</sub>
<div style="overflow: hidden;">
    <img style="width: 650px; height: 450px;" align="left" src="https://i.ibb.co/vXdr3GP/Screenshot-3.png">
</div>
Then we take the average of each node's necessary changes in the next layer and train the weights and biases.
<div style="overflow: hidden;">
    <img style="width: 450px; height: 450px;" align="left" src="https://i.ibb.co/2YQMmZc/Screenshot-4.png">
</div>
The weights are then all increased before it in proportion to the future need in the next layer. This is done recursively. Until the network is trained for that one number/final node values.
<div style="overflow: hidden;">
    <img style="width: 450px; height: 650px;" align="left" src="https://i.ibb.co/sv13bx0/Screenshot-5.png">
</div>
Then, we do this with all training values across the training set and finally average all the weight/bias changes.
<div style="overflow: hidden;">
    <img style="width: 450px; height: 650px;" align="left" src="https://i.ibb.co/sv13bx0/Screenshot-5.png">
</div>
<b>Forward Propagation</b>: Creating a starting value to begin gradient descent, normally arbitrary or random.
<b>Batches</b>: BaTCHERS ADD ANOTHER DIM BUT HOW ARE BATCHES FLATTENED
Data loader: Loads data as iterables

<h3>NN Vision</h3>
<b>Convolution</b>: Convolution means to pass an image with a filter or kernal. Con=with, volution=rotation<br>
<b>Image Kernel/Filter, convolution kernels</b>: A mathematical matrix applied to the pixels of an image. https://setosa.io/ev/image-kernels/<br>
<b>Padding</b>: Adding 0s at the edges of a picture to allow larger Convolutional filters to exist.<br>
<b>Pooling</b>: A culmination of previous layers into some type of pooling of that layer's output. This can me max, average, min, etc. This reduces the number of neurons before the fully connected layer.<br>
<b>Downsampling</b>: The main proponent of pooling layers is to downsample of reduce the number of neurons.<br>
<b>Fully connected layer</b>: The layer before the out layer which is essential a perceptron layer for the whole CNN<br>
<b>Out layer</b>: The final labels.<br>
What does the bottom number mean? <img src="https://i.imgur.com/di8eVMX.png">
<b>Channel/filter/depth</b>: The bottom number in the CNN Architectual diagram is a channel depicting the depth arbitrarily made by its user. It is used for backpropagation of the weights of each element of the grid.
<b>Dense</b>: A perceptron layer<br>

Good videos: <br>
https://www.youtube.com/watch?v=pj9-rr1wDhM&ab_channel=Futurology%E2%80%94AnOptimisticFuture
Pierian data Udemy videos

Also algorithm problems are the name of coding challenges.

A<h2>PyTorch</h2>

In [43]:
import torch

Classes:
<br>-Tensors(https://pytorch.org/docs/stable/tensors.html#torch-tensor)
<br>-Linear(https://pytorch.org/docs/stable/generated/torch.nn.Linear.html?highlight=linear#torch.nn.Linear): Linear is simple 1 neuron with multiple in features and out features.
<img src="https://i.gyazo.com/083b4389a1e15a510c92d3c0b87a7032.png">
<br>-nn.module(https://pytorch.org/docs/stable/generated/torch.nn.Module.html#module)

<h1>Tensors</h1>
<p>Tensors are the keystone data structure of PyTorch. They are essentially an x-dimensional array, based on Numpy. However they also store all math operations ever done on them.</p>
<img src="https://i.gyazo.com/91b6d467760f4a9a7d520ac60b7d7fed.png"><br>
<b>Basic terminology</b>
<br>-Properties: The actual value of an element in the XD array/tensor
<br>-Attributes: Description of the tensor
<br>&emsp;*Shape: Dimensions as described by tuple (2,2)
<br>&emsp;*Datatype
<br>&emsp;*Device: The device the calculations are done one(GPU/CPU)

In [17]:
print(torch.rand(1, 2)) #1 row 2 columns 1D
print(torch.rand(2)) #1 row 2 columns 1D
print(torch.rand(2, 2)) #2 row 2 columns 2D
print(torch.rand(3, 2, 2)) #3 z-rows 2 rows 2 columns or 3D
#Etc...

tensor([[0.4589, 0.7702]])
tensor([0.0088, 0.3050])
tensor([[0.5661, 0.0127],
        [0.0857, 0.0257]])
tensor([[[0.0890, 0.3729],
         [0.9415, 0.3840]],

        [[0.1914, 0.6926],
         [0.1592, 0.3946]],

        [[0.2893, 0.6881],
         [0.9912, 0.4915]]])


<b>Tensor Initializers</b>

In [21]:
print(torch.empty(2, 2)) #Actually undefined
print(torch.rand(2, 2)) #Between 0-1
print(torch.ones(2, 2)) #Ones
print(torch.zeros(2, 2))

tensor([[ 1.4013e-45,  1.3165e+00],
        [-3.1357e+00,  4.5915e-41]])
tensor([[0.2443, 0.8744],
        [0.8024, 0.6052]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


<b>From another tensor</b>
<p>The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.</p>

In [113]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(x_data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

tensor([[1, 2],
        [3, 4]])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5441, 0.0315],
        [0.4137, 0.1874]]) 



<b>Tensor structure datatypes</b>
<p>Tensors default to 32-bit floats but also include a lot of other types which can be used to initialize the X-D array.</p>

In [22]:
tensor = torch.ones(2, 2)
tensor.dtype

torch.float32

<p>Here is how we initialize the data type of a tensor.</p>

In [24]:
torch.ones(2, 2, dtype=torch.double)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

<p>dtypes list: </p><a href="https://pytorch.org/docs/stable/tensor_attributes.html" target="_blank">Here</a>

In [45]:
x = torch.ones(2, 2, dtype=torch.float16)
x.size()

torch.Size([2, 2])

In [54]:
#Has a different function thatn .rand. It seems to be between -3 and 3. No idea.
#Standard deviation of 1, mean of 0: https://youtu.be/MRqtXL2WX2M
torch.randn(2, 2)

tensor([[ 0.1245, -2.1239],
        [-0.2873,  2.7955]])

<b>Operations</b>

In [27]:
print(torch.ones(2, 2) + torch.ones(2, 2))

tensor([[2., 2.],
        [2., 2.]])


In [28]:
x = torch.ones(2, 2)
y = torch.ones(2, 2)
torch.add(x, y)

tensor([[2., 2.],
        [2., 2.]])

In [29]:
torch.sub(x, y)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
# torch.div(x, y)
# torch.mul(x, y)

<i>In-place modifiers...</i>
<p>Any functions with an underscore after is an in-place modifier.</p>

In [ ]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = torch.rand(2,2)
d = torch.rand(2,2)
a.add_(b) #Same as above modifies except it changes the variable in-place
b.sub_(c) #modifies b
c.mul_(d)
d.div_(a)

<i>Slicing</i>

In [31]:
torch.rand(3, 3)[:, 1:]

tensor([[0.8482, 0.3953],
        [0.2413, 0.9826],
        [0.0532, 0.3640]])

<i>Reshaping</i>

In [36]:
tensor = torch.rand(4,4)
print(tensor.view(16)) # shaping the array to a different array size, this is 1S=D
print(tensor.view(-1, 8)) # Shapes the array by whatever is a multiple of the second value...
print(tensor.view(-1, 2)) #See?

tensor([0.5439, 0.8369, 0.0447, 0.8875, 0.7600, 0.8869, 0.2966, 0.5552, 0.7150,
        0.5748, 0.6554, 0.6407, 0.9571, 0.4496, 0.1936, 0.3651])
tensor([[0.5439, 0.8369, 0.0447, 0.8875, 0.7600, 0.8869, 0.2966, 0.5552],
        [0.7150, 0.5748, 0.6554, 0.6407, 0.9571, 0.4496, 0.1936, 0.3651]])
tensor([[0.5439, 0.8369],
        [0.0447, 0.8875],
        [0.7600, 0.8869],
        [0.2966, 0.5552],
        [0.7150, 0.5748],
        [0.6554, 0.6407],
        [0.9571, 0.4496],
        [0.1936, 0.3651]])


<i>Casting to & from numpy</i>

In [41]:
import numpy as np
a = torch.ones(5)
print(a.numpy())
b = np.ones(5)
torch.from_numpy(b)

[1. 1. 1. 1. 1.]


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

<b>Create tensor on GPU</b>

In [42]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5, device=device)
    z = x + y #on GPU/VRAM
    np.ones(5) #on CPU/RAM

<b>Torch Gradients</b>

<a href='https://youtu.be/DbeIqrwb_dE?t=739'>Here</a> it appears gradients store previous functions and allow you to go to previous steps before specific calculations. This is like the gradients of color or the small changes of color.

This is a good one to supplement understanding of tensors and grads: https://www.youtube.com/watch?v=MswxJw-8PvE&ab_channel=ElliotWaite

<b>Linear Class</b>

In [130]:
import torch
from torch.nn import Linear
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1) #Random assign w and b, 1 input x & 1 output y
print(model.bias, model.weight)
x = torch.tensor([2.0])
print(model(x))

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)
tensor([0.5891], grad_fn=<AddBackward0>)


<h2>PyTorch Examples</h2>

In [114]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5*5 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square, you can specify with a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2) #https://production-media.paperswithcode.com/methods/MaxpoolSample2.png
        x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [119]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0063, -0.1084, -0.0087,  0.0010, -0.0668,  0.0633,  0.0031,  0.1187,
         -0.1184,  0.0324]], grad_fn=<AddmmBackward0>)


In [120]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [121]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.6274, grad_fn=<MseLossBackward0>)


The gradient is the slope of the function of a tensor at a given dimension.

In [129]:
import torch
x = torch.tensor([1.0, 1.0], requires_grad=True)
y = 2*x**2
y.backward() #Go back a function
print(x.grad) #Determine the slope with respect to itself at the previous function.

RuntimeError: grad can be implicitly created only for scalar outputs

nn.module is a parent class used to create custom Neural network implementations. Some functions are called automatically, like forward.

forward is forward propogation.

<h2>Pandas</h2>
<p>Built off of numpy to calculate data</p>

<h3>Series</h3>
<p>Numpy Array but with named index along with numerical index. Also the data types can be mixed</p>

In [55]:
import numpy as np
import pandas as pd

<b>Basic constructor</b>

In [58]:
labels = ['a','b', 'c']
mylist = np.array([1, 2, 3])

d = {'a': 1, 'b': 2, 'c': 3}

print(pd.Series(data=mylist, index=labels))
print(pd.Series(data=d))
print(pd.Series(data=[3, 'a', True]))

a    1
b    2
c    3
dtype: int32
a    1
b    2
c    3
dtype: int64
0       3
1       a
2    True
dtype: object


<b>Grabbing by indices</b>

In [60]:
series = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
series['b']

2

<b>Adding series</b>
<p>Adds by series names and extends the series to the longest one.</p>

In [61]:
series = pd.Series([1, 2, 3, 4], index=['a', 'e', 'c', 'd'])
series2 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
series + series2

a    2.0
b    NaN
c    6.0
d    8.0
e    NaN
dtype: float64

<h3>Dataframes</h3>
<p>Series grouped together, sharing indices. This is basically tabular data like csv</p>

In [ ]:
import numpy as np
import pandas as pd

<b>Initialize</b>

In [85]:
from numpy.random import randn
np.random.seed(101)

ran_mat = randn(5, 4)
print(ran_mat)

#Initialize dataframe
df = pd.DataFrame(data=ran_mat, index=['a', 'b', 'c', 'd', 'e'], columns=['w', 'x', 'y', 'z'])
df

[[ 2.70684984  0.62813271  0.90796945  0.50382575]
 [ 0.65111795 -0.31931804 -0.84807698  0.60596535]
 [-2.01816824  0.74012206  0.52881349 -0.58900053]
 [ 0.18869531 -0.75887206 -0.93323722  0.95505651]
 [ 0.19079432  1.97875732  2.60596728  0.68350889]]


w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

<b>Grab by indices</b>
<p>loc is rows and default is columns</p>

<i>Columns are default</i>

In [83]:
print(df['x'])
df[['w', 'z']]

a    0.628133
b   -0.319318
c    0.740122
d   -0.758872
e    1.978757
Name: x, dtype: float64


w         z
a  2.706850  0.503826
b  0.651118  0.605965
c -2.018168 -0.589001
d  0.188695  0.955057
e  0.190794  0.683509

<i>Rows are called by loc. It is a flipped dataframe</i>

In [94]:
print(df.loc['e'])
print(df.iloc[0])
df.loc[['a', 'c']]

w    0.190794
x    1.978757
y    2.605967
z    0.683509
Name: e, dtype: float64
w    2.706850
x    0.628133
y    0.907969
z    0.503826
Name: a, dtype: float64


<b>Create a new column</b>
<p>Refer to the column as a new indice and it adds to the dataframe</p>

In [75]:
df['NEW'] = df['w'] + df['y']
df

w         x         y         z       NEW
a  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762

<b>Drop an axis</b>
<p>Drops an axis by name</p>

In [76]:
df.drop('NEW', axis=1, inplace=True) #axis 0 = row, axis 1 = column, default axis 0
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [77]:
df.drop('e', inplace=True)
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057

<b>Boolean Dataframes</b>

In [95]:
df_bool = df > 0.5
df_bool

w      x      y      z
a   True   True   True   True
b   True  False  False   True
c  False   True   True  False
d  False  False  False   True
e  False   True   True   True

In [96]:
df[df > 0]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118       NaN       NaN  0.605965
c       NaN  0.740122  0.528813       NaN
d  0.188695       NaN       NaN  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [98]:
#filter row
df[df['w'] > 0]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [103]:
#Conditional selection with pandas
con1 = df['w'] > 0
con2 = df['y'] > 0
df[(con1) & (con2)]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
e  0.190794  1.978757  2.605967  0.683509

<i>Change indices</i>

<p>You have to insert the column then set the index</p>

In [107]:
new_ind = 'tx ca ma ny wa'.split()
df['states'] = new_ind
df.set_index('states')

w         x         y         z
states                                        
tx      2.706850  0.628133  0.907969  0.503826
ca      0.651118 -0.319318 -0.848077  0.605965
ma     -2.018168  0.740122  0.528813 -0.589001
ny      0.188695 -0.758872 -0.933237  0.955057
wa      0.190794  1.978757  2.605967  0.683509

<b>Misc Notes</b>

In [108]:
#Memory usage, column information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   w       5 non-null      float64
 1   x       5 non-null      float64
 2   y       5 non-null      float64
 3   z       5 non-null      float64
 4   states  5 non-null      object 
dtypes: float64(4), object(1)
memory usage: 400.0+ bytes


In [ ]:
#Dtype of columns
df.dtype

In [109]:
#Statistics of columns
df.describe()

w         x         y         z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

<p><b>inplace</b> parameter makes the function in place</p>